### ISSUE TITLE
FlowStack stopped working property with Date Picker

### ISSUE THREAD

**Issue by edwardsanchez** [nathantannar4/Turbocharger#5]
When putting a DatePicker in the stack, the label stretches to fill the space.
![GIVGfbybQAAKKOe](https://github.com/nathantannar4/Turbocharger/assets/40975/510631e9-f7cd-450b-9ebc-0c503495b2ab)

And if I add fixedSize() the whole stack becomes center aligned.
![GIVJfIabgAA4Es0](https://github.com/nathantannar4/Turbocharger/assets/40975/dd45d1e8-b9b4-4c7a-89a0-7d242001828e)

**Comment by edwardsanchez** [comment]
Adding frame(maxWidth: infinity, alignment: .leading) fixed the problem
<img width="463" alt="image" src="https://github.com/nathantannar4/Turbocharger/assets/40975/738179c5-1bb2-4dbd-8bd7-d8ca83fc4127">

**Comment by nathantannar4** [comment]
This is expected behaviour because the DatePicker SwiftUI view is greedy and wants to take the max size it's proposed by the layout. 

fixedSize() on the DatePicker is the right approach here. You then need the frame(maxWidth: infinity) because then the stacks sizeToFit is now smaller than what's it's proposed by its parent. This matches the behaviour of HStack.
